version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: user
      MYSQL_PASSWORD: adm_dev25*
    ports:
      - "3306:3306"
